fix/content-outdated
italia/design-linee-guida-docs pull request #27
Opened 2022-11-09 11:22 UTC by Fupete

2022-11-09 13:18 UTC, pedromaria88 requested changes

2022-11-09 13:18 UTC, pedromaria88 commented on README.md
> +# :warning: Questa versione delle linee guida è superata
```suggestion
# :warning: Queste Linee Guida sono superate, rimangono qui visionabili come memoria storica
```

2022-11-09 13:18 UTC, pedromaria88 commented on README.md
> +I riferimenti più attuali sono:
```suggestion
I riferimenti attuali sono:
```

2022-11-09 13:18 UTC, pedromaria88 commented on README.md
> +- il **[Manuale operativo di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/)** ([repository GitHub](https://github.com/italia/manuale-operativo-design-docs)) e
```suggestion
- il **[Manuale operativo di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/)** ([repository GitHub](https://github.com/italia/manuale-operativo-design-docs)) che raccoglie ed evolve gli aspetti operativi delle precedenti linee guida al presente link, e le altre risorse messe a disposizione come strumento a supporto della Pubblica Amministrazione e dei suoi fornitori dal progetto [Designers Italia](https://designers.italia.it).
```

2022-11-09 14:20 UTC, bfabio commented on banner.rst
> +    - le **`Linee guida di design per i siti e i servizi digitali della PA<https://docs.italia.it/italia/design/lg-design-servizi-web>`_** emesse a norma CAD ex. Art 71;
```suggestion
    - le **`Linee guida di design per i siti e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web>`_** emesse a norma CAD ex. Art 71;
```

2022-11-09 14:21 UTC, bfabio commented on banner.rst
> +    - il **`Manuale operativo di design<https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/>`_** e le altre risorse messe a disposizione come strumento a supporto della Pubb
```suggestion
    - il **`Manuale operativo di design <https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/>`_** e le altre risorse messe a disposizione come strumento a supporto della Pubblica Amministrazione e dei suoi fornitori dal progetto **`Designers Italia <https://designers.italia.it>`_**.
```

2022-11-09 14:28 UTC, danielaiozzo commented on README.md
> +I riferimenti più attuali sono:
```suggestion
I riferimenti normativi attualmente in vigore sono:
```

2022-11-09 14:28 UTC, danielaiozzo commented on README.md
> +I riferimenti più attuali sono:
forse potremmo rinforzare ulteriormente @pedromaria88 che dici?

2022-11-09 14:31 UTC, danielaiozzo commented on banner.rst
> +    `Per approfondire <https://designers.italia.it/notizie/Nuove-Linee-guida-e-Manuale-operativo-di-design/>`_.
```suggestion
    `Per approfondire <https://designers.italia.it/notizie/Nuove-Linee-guida-e-Manuale-operativo-di-design/>`_
```

2022-11-09 16:01 UTC, bfabio commented on banner.rst
> +    - il **`Manuale operativo di design<https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/>`_** e le altre risorse messe a disposizione come strumento a supporto della Pubb
@Fupete pare che RST non supporti markup innestato. Niente link in grassetto :disappointed:

2022-11-09 16:01 UTC, bfabio commented on banner.rst
> +    - le **`Linee guida di design per i siti e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web>`_** emesse a norma CAD ex. Art 71;
```suggestion
    - le `Linee guida di design per i siti e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web>`_ emesse a norma CAD ex. Art 71;
```

2022-11-09 16:07 UTC, Fupete commented on README.md
> +I riferimenti più attuali sono:
@danielaiozzo il manuale non è normativo.

2022-11-09 16:51 UTC, danielaiozzo requested changes

2022-11-09 16:51 UTC, danielaiozzo commented on README.md
> +- le **[Linee guida di design per i siti internet e i servizi digitali della PA](https://docs.italia.it/italia/design/lg-design-servizi-web/)** ([repository GitHub](https://github.com/italia/lg-desig
```suggestion
- le **[Linee guida di design per i siti internet e i servizi digitali della PA](https://docs.italia.it/italia/design/lg-design-servizi-web/)** ([repository GitHub](https://github.com/italia/lg-design-servizi-web/)), riferimento normativo in vigore, emesse a norma CAD ex. Art 71;
```

2022-11-09 16:51 UTC, danielaiozzo commented on README.md
> +- il **[Manuale operativo di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/)** ([repository GitHub](https://github.com/italia/manuale-operativo-design-docs)) ch
```suggestion
- il **[Manuale operativo di design](https://docs.italia.it/italia/designers-italia/manuale-operativo-design-docs/)** ([repository GitHub](https://github.com/italia/manuale-operativo-design-docs)) che raccoglie ed evolve gli aspetti operativi delle linee guida emesse a norma CAD e le altre risorse messe a disposizione come strumento a supporto della Pubblica Amministrazione e dei suoi fornitori dal progetto [Designers Italia](https://designers.italia.it).
```

2022-11-09 16:51 UTC, danielaiozzo commented on banner.rst
> +    I riferimenti più attuali sono:
```suggestion
    I riferimenti attuali sono:
```

2022-11-09 16:51 UTC, danielaiozzo commented on banner.rst
> +    - le `Linee guida di design per i siti e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web>`_ emesse a norma CAD ex. Art 71;
```suggestion
    - le `Linee guida di design per i siti e i servizi digitali della PA <https://docs.italia.it/italia/design/lg-design-servizi-web>`_ emesse a norma CAD ex. Art 71 e riferimento normativo in vigore;
```

2022-11-09 17:09 UTC, danielaiozzo requested changes

2022-11-09 17:09 UTC, danielaiozzo commented on banner.rst
> +  I riferimenti più attuali sono:
```suggestion
  I riferimenti attuali sono:
```

2022-11-10 08:39 UTC, bfabio commented on banner.rst
> +.. admonition:: Queste linee guida sono superate
```suggestion
.. admonition:: Queste linee guida sono superate
  :class error display-page

```

2022-11-10 08:41 UTC, bfabio commented on banner.rst
> +  :class error display-page
```suggestion
  :class: error display-page
```

2022-11-10 08:45 UTC, merged